local editor = require("graph_editor.scripts.editor")

function init(self)
	msg.post(".", "acquire_input_focus")
	editor.init()
end

function update(self, dt)
	editor.update(dt)
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	editor.input(action_id, action)
end
