embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/graph_editor/assets/models/direction.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/graph_editor/assets/materials/unlit/model_unlit_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/graph_editor/assets/images/green.png\"\n"
  "  }\n"
  "}\n"
  ""
}
